// MIoT 设备实测词条词典（v1.6.16）：从生产 123 台设备 / 52 个规格全量提取的
// 未翻译英文参数（802 个服务/属性/动作/事件名 + 511 个枚举值），人工翻译成中文。
// 由 GET /api/mihome/terms 下发给前端：① 详情页名称回退查此表 ② 「参数翻译」tab 分组展示。
// 键统一小写匹配（zh() 已做 toLowerCase）；系列词条用 seq() 展开。
const seq = (zhName, prefix, suffixes, sep) => String(suffixes).split('').map((c, i) => [prefix + (sep ? sep : '-') + c, `${zhName} ${String.fromCharCode(65 + i)}`]);

const NAME_PAIRS = [
  ['ability', '能力支持'], ['abnormal-condition', '异常状况'], ['abnormal-sound', '异响'],
  ['abnormal-sound-detection', '异响检测'], ['access-mode', '接入模式'], ['action-par', '动作参数'],
  ['action-result', '动作结果'], ['active-fav-area', '当前看护区域'], ['add-order-clean', '添加顺序清扫'],
  ['add-remote', '添加遥控器'], ['add-user-sweep-setting', '添加用户清扫设置'], ['addremotecontrol', '添加遥控器'],
  ['adv-func-setting', '高级功能设置'], ['agree-privacy', '同意隐私条款'], ['ai-detection', 'AI 检测'],
  ['ai-frame', 'AI 画面'], ['ai-sensitivity', 'AI 灵敏度'], ['air-purifier-favorite', '净化器收藏档'],
  ['alarm-interval', '报警间隔'], ['all-onoff', '总开关'], ['all-switch-status', '全部开关状态'],
  ['anti-flicker', '防频闪'], ['area-count', '区域数量'], ['area-detect-attr', '区域检测属性'],
  ['area-detect-live', '区域检测画面'], ['area-detect-switch', '区域检测开关'], ['area-display-switch', '区域显示开关'],
  ['area-shape', '区域形状'], ['area-support-concave', '区域支持凹形'], ['audio-attribute', '音频参数'],
  ['audio-bit-width', '音频位宽'], ['audio-channel', '声道'], ['audio-codec', '音频编码'],
  ['audio-codec-type', '音频编码类型'], ['audio-id', '音频 ID'], ['audio-smp-rate', '音频采样率'],
  ['authorization-type', '鉴权方式'], ['auto-dust-arrest', '自动集尘'], ['auto-identify', '自动识别'],
  ['auto-mop-dry', '拖布自动烘干'], ['auto-power-on', '来电自启动'], ['auto-room-partition', '自动房间分区'],
  ['auto-screen-brightness', '屏幕自动亮度'], ['auto-screen-off', '自动熄屏'], ['auto-screen-on', '自动亮屏'],
  ['auto-update', '自动更新'], ['auto-water-change', '自动换水'], ['auto-water-change-installed', '自动换水模块已安装'],
  ['babycry-detection-switch', '婴儿哭声检测'], ['back-locking', '室内反锁'], ['back-mop-wash', '后拖布清洗'],
  ['base-station-working-status', '基站工作状态'], ['basic-func-setting', '基础功能设置'], ['battery-status', '电池状态'],
  ['beat-mode-set', '节拍模式设置'], ['bind-wifi', '绑定 Wi-Fi'], ['binding-id', '绑定 ID'],
  ['binding-id-b', '绑定 ID B'], ['biorhythmonoff', '生物节律开关'], ['biorhythmrepeat', '生物节律重复'],
  ['biorhythmreset', '生物节律重置'], ['bk-light', '背景灯'], ['bk-onoff', '背景灯开关'],
  ['blow-high', '吹风高档'], ['blow-low', '吹风低档'], ['breathing-mode-set', '呼吸模式设置'],
  ['breathingtypespeed', '呼吸类型速度'], ['brightness-add', '亮度+'], ['brightness-dec', '亮度−'],
  ['brightness-delta', '亮度增量'], ['brightness-down', '亮度−'], ['brightness-switch', '亮度开关'],
  ['brightness-up', '亮度+'], ['brush-cleaner', '滚刷'], ['brush-life-level', '滚刷寿命'],
  ['build-map-complete', '建图完成'], ['button-type', '按键类型'], ['buzzer-function', '蜂鸣器'],
  ['camera-capacity', '摄像头能力'], ['camera-control', '摄像头控制'], ['camera-fav-area', '摄像头常用区域'],
  ['camera-ipc-cloud', '摄像头云服务'], ['camera-stream-for-amazon-alexa', 'Alexa 视频流'],
  ['camera-stream-for-google-home', 'Google Home 视频流'], ['cancel-water-self-check', '取消水质自检'],
  ['capacity', '容量'], ['carpet-avoidance', '避让地毯'], ['carpet-boost', '地毯增压'],
  ['carpet-cleaning-method', '地毯清扫方式'], ['carpet-display', '地毯显示'], ['carpet-obj-name', '地毯名称'],
  ['carpet-object', '地毯对象'], ['charging-status', '充电状态'], ['child-detection', '儿童检测'],
  ['child-lock-status', '童锁状态'], ['child-protected-status', '儿童保护状态'], ['clean-record', '清扫记录'],
  ['clean-times', '清扫次数'], ['cleaning-area', '清扫面积'], ['cleaning-time', '清扫时长'],
  ['clear-map', '清除地图'], ['clearallrmtinfo', '清除全部遥控数据'], ['click', '单击'],
  ['clock', '时钟'], ['clock-key', '时钟按键'], ['close-abnormal-card', '关闭异常卡片'],
  ['close-up-function-status', '特写功能状态'], ['cloud-video-id', '云端视频 ID'], ['colortemperatre-dec', '色温−'],
  ['colortemperature-add', '色温+'], ['colortemperature-sw', '色温开关'], ['common-params', '通用参数'],
  ['config', '配置'], ['contact-state', '门磁状态'], ['continue-build-map', '继续建图'],
  ['continue-sweep', '继续清扫'], ['countdown-info', '倒计时信息'], ['countdown-time', '倒计时时间'],
  ['cruise', '巡航'], ['cruise-cycle', '巡航周期'], ['cruise-end-time', '巡航结束时间'],
  ['cruise-ended', '巡航已结束'], ['cruise-mode', '巡航模式'], ['cruise-position', '巡航点位'],
  ['cruise-repetition', '巡航重复'], ['cruise-start-time', '巡航开始时间'], ['cruise-started', '巡航已开始'],
  ['cruise-switch', '巡航开关'], ['ct-adjust-alexa', '色温调节（Alexa）'], ['ct-delta', '色温增量'],
  ['ctldec', '调低'], ['ctlinc', '调高'], ['ctrl', '控制'], ['cur-voice', '当前音色'],
  ['current-cleaning-config', '当前清扫配置'], ['current-map-id', '当前地图 ID'], ['current-no-disturb', '当前免打扰'],
  ['current-physical-control-lock', '物理按键锁定状态'], ['current-time', '当前时间'],
  ['curtain-adv-ctrl', '窗帘高级控制'], ['curtain-ext', '窗帘扩展'], ['curtain-manually-closed', '窗帘被手动关闭'],
  ['curtain-manually-opened', '窗帘被手动打开'], ['curtain-rollup-ctrl', '窗帘卷起控制'],
  ['curtain-scene-ctrl', '窗帘场景控制'], ['custom-function', '自定义功能'], ['customized-for-wifi', 'Wi-Fi 专用'],
  ['customized-wifi-lock', 'Wi-Fi 锁定'], ['data', '数据'], ['datas', '数据集'],
  ['default', '默认'], ['default-lumctl', '默认亮度控制'], ['default-power-on-state', '默认开机状态'],
  ['defaultonoffstate', '默认开关状态'], ['defaultparareset', '恢复默认参数'], ['del-remote', '删除遥控器'],
  ['del-user-sweep-setting', '删除用户清扫设置'], ['delay-off-end', '延时关闭结束'], ['delay-remain-time', '延时剩余时间'],
  ['delay-switch', '延时开关'], ['delay-time', '延时时间'], ['delete-map', '删除地图'],
  ['delete-order-clean', '删除顺序清扫'], ['delete-remote-control', '删除遥控器'], ['deleteremote', '删除遥控'],
  ['demo', '演示'], ['demo-mode-status', '演示模式状态'], ['demo-volume', '演示音量'],
  ['detected-babycry-event', '检测到婴儿哭声'], ['detection-sensitivity', '检测灵敏度'],
  ['detergent-depletion-reminder', '洗涤剂用尽提醒'], ['detergent-left-level', '洗涤剂余量'],
  ['detergent-management', '洗涤剂管理'], ['detergent-self-delivery', '洗涤剂自动投放'],
  ['detergent-self-delivery-level', '洗涤剂投放量'], ['device-be-reset', '设备被重置'], ['device-mode', '设备模式'],
  ['dhcp-server-mac-adress', 'DHCP 服务器 MAC 地址'], ['dialog-ejected', '弹窗拔卡'], ['dimming', '调光'],
  ['display-state', '显示状态'], ['distortion-crt-osdx', '畸变校正 OSD X'], ['distortion-crt-osdy', '畸变校正 OSD Y'],
  ['door', '门'], ['door-ajar-volume', '门虚掩提示音量'], ['door-close-volume', '关门提示音量'],
  ['door-not-closed', '门未关'], ['door-open-time', '开门时长'], ['door-open-volume', '开门提示音量'],
  ['doorbell', '门铃'], ['doorbell-light', '门铃指示灯'], ['doorbell-ring', '门铃响铃'],
  ['doorbell-switch', '门铃开关'], ['doorbell-volume', '门铃音量'], ['double-click', '双击'],
  ['download-progress', '下载进度'], ['download-status', '下载状态'], ['download-voice', '下载语音'],
  ['dry-complete', '烘干完成'], ['drying-time', '烘干时长'], ['dust-arrest-complete', '集尘完成'],
  ['dust-arrest-frequency', '集尘频率'], ['dust-bag', '尘袋'], ['dust-bag-left-time', '尘袋剩余时间'],
  ['dust-bag-life-level', '尘袋寿命'], ['dynamicmode', '动态模式'], ['edge-sweep-frequency', '沿边清扫频率'],
  ['edge-swing-tail-sweep', '沿边摆尾清扫'], ['emit-virtual-event', '发送虚拟事件'],
  ['enable-manual-draw-curtain', '允许手动拉窗帘'], ['enable-mop-wash', '启用拖布清洗'],
  ['enable-time-period', '启用时间段'], ['enter-remote', '进入遥控'], ['event', '事件'],
  ['exception-occurred', '发生异常'], ['execute-text-directive', '执行文本指令'], ['exit-remote', '退出遥控'],
  ['exit-remote-dialog', '退出遥控对话框'], ['expiration-time', '有效期'], ['exponentialdim', '亮度指数变化'],
  ['extra-device-information', '扩展设备信息'], ['face-detection', '人脸检测'], ['face-detection-switch', '人脸检测开关'],
  ['face-sleep-time', '人脸休眠时间'], ['face-switch', '人脸开关'], ['face-volume', '人脸提示音量'],
  ['factory-reset', '恢复出厂设置'], ['fade-time', '渐变时间'], ['family-guard', '家庭看护'],
  ['family-guard-config', '家庭看护配置'], ['fan-control', '风扇控制'], ['fault-ids', '故障项'],
  ['fav-area', '常用区域'], ['favorite-fan-level', '收藏风速档'], ['filter', '滤芯'],
  ['filter-used-time', '滤芯已用时间'], ['fire-smoke', '烟火'], ['fire-smoke-alarm-switch', '烟火报警开关'],
  ['fire-smoke-event', '烟火事件'], ['fire-smoke-switch', '烟火开关'], ['flex-switch', '灵活开关'],
  ['fragrance-out-time', '香氛出香时长'], ['frequency-mop-wash', '拖布清洗频率'],
  ['frequency-mop-wash-no-tank', '拖布清洗频率（无水箱）'], ['func-config', '功能配置'], ['function', '功能'],
  ['functions-enable', '功能启用'], ['get', '获取'], ['get-download-status', '获取下载状态'],
  ['get-history-obj', '获取历史对象'], ['get-room-configs', '获取房间配置'], ['get-stream-configuration', '获取流配置'],
  ['get-system-info', '获取系统信息'], ['get-user-define', '获取自定义'], ['get-vacuum-route', '获取清扫路径'],
  ['glimmer-full-color', '微光全彩'], ['gop-value', 'GOP 值'], ['hand-gesture-detection-switch', '手势检测开关'],
  ['hand-gesture-name', '手势名称'], ['handxclose', '合手（关闭手势）'], ['handxopen', '张手（打开手势）'],
  ['heating', '加热'], ['hl-baby-cry', '婴儿哭声'], ['hl-camera-switch', '摄像头开关'], ['hl-delete-voice', '删除语音'],
  ['hl-download-voice', '下载语音'], ['hl-enter-day-mode', '进入白天模式'], ['hl-enter-night-mode', '进入夜晚模式'],
  ['hl-event-motion', '移动事件'], ['hl-get-custom-voice', '获取自定义语音'], ['hl-get-max-connect', '获取最大连接数'],
  ['hl-people-motion', '人体移动'], ['hl-set-custom-voice', '设置自定义语音'], ['hl-set-rect', '设置区域'],
  ['hl-set-timezone', '设置时区'], ['hl-speaker-voice', '播报语音'], ['hl-upload-log', '上传日志'],
  ['hl-upload-recode', '上传录像'], ['hl-voice-switch', '语音开关'], ['homepage', '主页'],
  ['horizontal-swing-included-angle', '左右摆风角度'], ['hot-water-mop-wash', '热水洗拖布'],
  ['human-close-up', '人物特写'], ['human-detection', '人体检测'], ['human-tracking', '人物追踪'],
  ['identity-id', '身份 ID'], ['identity-reid', '身份跨镜识别'], ['idle-time', '空闲时长'],
  ['illumination-degree', '光照度'], ['image-distortion-correction', '图像畸变校正'], ['image-rollover', '画面翻转'],
  ['image-snapshot', '快照图片'], ['imilab-timer', '定时器'], ['induction-switch', '感应开关'],
  ['intelligent-speaker', '智能音箱'], ['interactive', '互动'], ['interactive-switch', '互动开关'],
  ['into-fav-area', '进入常用区域'], ['ir-turned-off', '红外夜视已关'], ['ir-turned-on', '红外夜视已开'],
  ['key-call', '按键呼叫'], ['key-call-start', '按键呼叫开始'], ['key-call-status', '按键呼叫状态'],
  ['key-name-display', '按键名称显示'], ['key-name-refresh', '按键名称刷新'], ['key-relay-map', '按键映射'],
  ['last-clean-time', '上次清扫时间'], ['lcd-show-mode', '屏显模式'], ['leave-home', '离家模式'],
  ['led-strip', '灯带'], ['libattery-status', '锂电池状态'], ['libattery-temp', '锂电池温度'],
  ['light-extension', '灯光扩展'], ['light-time', '灯亮时长'], ['lightdimtime', '亮度渐变时间'],
  ['lightminlum', '最小亮度'], ['lightofftime', '熄灯时间'], ['lightontime', '亮灯时间'],
  ['limit-clr', '限位清除'], ['limit-run', '限位运行'], ['limit-set', '限位设置'],
  ['linkage-coordinate', '联动坐标'], ['linkage-switch', '联动开关'], ['live-video-enable-time-period', '直播可用时间段'],
  ['live-video-streaming', '视频直播中'], ['live-video-valid-time', '直播有效时长'], ['location-status', '位置状态'],
  ['lock-action', '锁动作'], ['lock-event', '门锁事件'], ['lock-opened', '门锁已打开'],
  ['lock-region', '锁定区域'], ['lock-region-attr', '锁定区域属性'], ['lock-sensitivity', '锁灵敏度'],
  ['lock-setting-key', '门锁设置按键'], ['log', '日志'], ['log-b', '日志 B'], ['log-k', '日志 K'],
  ['logdata', '日志数据'], ['long-press', '长按'], ['long-time-no-humang', '长时间无人'],
  ['louder-sound', '声音变大'], ['low-battery', '电量低'], ['low-rinse-level', '低漂洗档'],
  ['low-water-softener-level', '软水盐余量低'], ['lowest-brightness', '最低亮度'],
  ['lumdec', '亮度−'], ['luminc', '亮度+'], ['manual-check-results', '人工检查结果'],
  ['manual-draw-speed-adaptive', '手拉速度自适应'], ['map-3d-info', '3D 地图信息'],
  ['map-complete-dialog', '建图完成弹窗'], ['map-management', '地图管理'], ['map-obj-name', '地图对象名称'],
  ['master', '主控'], ['master-slave-switch', '主从开关'], ['memory-card-management', '存储卡管理'],
  ['merge-rooms', '合并房间'], ['message', '消息'], ['message-state', '消息状态'], ['mibrain', '小爱同学'],
  ['mibrain-level', '小爱音量档'], ['mico-level', '麦克风音量档'], ['microphone', '麦克风'],
  ['modify-order-clean', '修改顺序清扫'], ['modify-user-sweep-setting', '修改用户清扫设置'],
  ['mop-left-time', '拖布剩余时间'], ['mop-status', '拖布状态'], ['mop-wash-complete', '拖布清洗完成'],
  ['mop-water-output-level', '拖布出水量'], ['mop-water-output-level-no-tank', '拖布出水量（无水箱）'],
  ['motion-detected', '检测到移动'], ['motion-detection', '移动侦测'], ['motion-detection-end-time', '移动侦测结束时间'],
  ['motion-detection-repetition', '移动侦测重复'], ['motion-detection-start-time', '移动侦测开始时间'],
  ['motion-state-toggle', '移动状态切换'], ['motion-tracking', '移动追踪'], ['motor-calibrate', '电机校准'],
  ['motor-reverse', '电机反转'], ['move-det-sens', '移动检测灵敏度'], ['move-detection', '移动检测'],
  ['multifunction-button', '多功能按键'], ['my-scene-act', '我的场景执行'], ['my-scene-mode', '我的场景模式'],
  ['my-scene-mode-firs', '我的场景模式一'], ['my-scene-mode-second', '我的场景模式二'],
  ['my-scene-mode-third', '我的场景模式三'], ['name', '名称'], ['name-synchronization', '名称同步'],
  ['network-changed', '网络已变更'], ['night-light-switch', '夜灯开关'], ['night-shot', '夜视'],
  ['nightenable', '夜间模式启用'], ['nightmodeonoff', '夜间模式开关'], ['no-disturb', '免打扰'],
  ['no-huamn-appear', '无人出现'], ['no-human-appear', '无人出现'], ['no-human-inteval', '无人间隔'],
  ['no-motion-duration', '无移动时长'], ['non-vip-offset-num', '非会员偏移量'], ['notice', '通知'],
  ['number', '编号'], ['object-motion', '物体移动'], ['obstacle-avoidance-strategy', '避障策略'],
  ['on-or-brightness', '开关或亮度'], ['on-or-colortemp', '开关或色温'], ['open-time-set', '开启时间设置'],
  ['openrmtbindwindow', '打开遥控绑定窗口'], ['operation-id', '操作 ID'], ['operation-method', '操作方式'],
  ['operation-position', '操作位置'], ['order-clean', '顺序清扫'], ['other-functions', '其他功能'],
  ['out-fav-area', '离开常用区域'], ['over-power', '过载功率'], ['over-power-limit', '过载功率上限'],
  ['overheat-alarm', '过热报警'], ['overtime', '超时'], ['p2p-stream', 'P2P 流'],
  ['palm-vein', '掌静脉'], ['panel-service', '面板服务'], ['parareset', '参数重置'],
  ['parcel-detection', '包裹检测'], ['parcel-move', '包裹移动'], ['pause-build-map', '暂停建图'],
  ['pause-sweeping', '暂停清扫'], ['people-fence-in', '有人进入围栏'], ['people-fence-out', '有人离开围栏'],
  ['people-number', '人数'], ['pet-appeared', '宠物出现'], ['pet-detection-switch', '宠物检测开关'],
  ['pet-tracking', '宠物追踪'], ['pets-type', '宠物类型'], ['phone-call-start', '来电开始'],
  ['picture-show', '图片展示'], ['pilot-switch', '指示灯开关'], ['pir-level', '人体感应灵敏度'],
  ['pir-onoff', '人体感应开关'], ['pir-state', '人体感应状态'], ['play-loop-mode', '循环播放模式'],
  ['play-music', '播放音乐'], ['play-radio', '播放电台'], ['play-text', '播放文本'],
  ['playing-state', '播放状态'], ['plugin-info-remind', '插件信息提醒'], ['pop-up', '弹出'],
  ['power-alarm-settings', '电源报警设置'], ['power-consumption-accumulation-way', '电量累计方式'],
  ['power-enable', '电源使能'], ['power-frequency', '电源频率'], ['power-no-ptz-camera', '断电记忆（非云台机）'],
  ['power-ptz-camera', '断电记忆（云台机）'], ['preservation-left-time', '保鲜剩余时间'],
  ['preview-test', '预览测试'], ['ptc-bath-heater', 'PTC 浴霸'], ['ptz-calibrate', '云台校准'],
  ['ptz-camera', '云台机'], ['query-id', '查询 ID'], ['record-someone-stay', '记录有人停留'],
  ['recording-mode', '录像模式'], ['recoveryordefault', '恢复或默认'], ['region-privacy', '区域隐私'],
  ['region-privacy-area', '隐私区域'], ['region-privacy-switch', '隐私区域开关'],
  ['regular-preservation-data', '定期保鲜数据'], ['reid-event', '跨镜识别事件'], ['reid-switch', '跨镜识别开关'],
  ['relay-event', '中继事件'], ['remaining-recording-duration', '剩余可录像时长'], ['remote', '遥控器'],
  ['remote-cmd', '遥控指令'], ['remote-control-addable', '可添加遥控器'], ['remote-control-identify', '遥控器识别'],
  ['remote-control-list', '遥控器列表'], ['remote-control-management', '遥控器管理'], ['remote-get', '获取遥控'],
  ['remote-htype', '遥控类型 H'], ['remote-ltype', '遥控类型 L'], ['remote-pair-success', '遥控配对成功'],
  ['remote-screen-off', '远程熄屏'], ['remoteid', '遥控器 ID'], ['remoter-cmd', '遥控指令'],
  ['remoter-ctrl', '遥控控制'], ['repeat', '重复'], ['reservation-complete-time', '预约完成时间'],
  ['reservation-left-time', '预约剩余时间'], ['reservation-start', '预约开始'], ['reserve', '预约'],
  ['reset-brush-life', '重置滚刷寿命'], ['reset-detergent-management-level', '重置洗涤剂量'],
  ['reset-dust-bag-life', '重置尘袋寿命'], ['reset-filter-life', '重置滤芯寿命'], ['reset-mop-life', '重置拖布寿命'],
  ['resolution-types', '分辨率类型'], ['rest', '休息'], ['restart-device', '重启设备'],
  ['restricted-sweep-areas', '禁扫区'], ['restricted-walls', '虚拟墙'], ['reverse', '反转'],
  ['rhythm-function', '律动功能'], ['rhythmic-function', '律动功能'], ['ringtone', '铃声'],
  ['rinse-left-level', '漂洗剂余量'], ['rinse-management', '漂洗管理'], ['room-information', '房间信息'],
  ['room-refresh', '房间刷新'], ['room-size', '房间面积'], ['room-size-configed', '已配置房间面积'],
  ['run-status', '运行状态'], ['rx-one', '接收一'], ['rx-two', '接收二'], ['save-map', '保存地图'],
  ['scene-mode-act', '场景模式执行'], ['screen-off-time', '熄屏时间'], ['screen-on-duration', '亮屏时长'],
  ['screen-picture-idx', '屏保图片序号'], ['screen-sleep-mode', '屏幕休眠模式'], ['sectiononoff', '分段开关'],
  ['seek', '跳转'], ['seek-time', '跳转时间'], ['self-check', '自检'], ['self-check-complete', '自检完成'],
  ['self-check-items', '自检项目'], ['self-check-results', '自检结果'], ['send-data', '发送数据'],
  ['sensing-state', '感应状态'], ['serial-no', '序列号'], ['set-map', '设置地图'], ['set-map-name', '设置地图名称'],
  ['set-room-clean-configs', '设置房间清扫配置'], ['set-zone', '设置区域'], ['setting', '设置'],
  ['silent-execution', '静默执行'], ['sk-ch-cmd', '通道指令'], ['sk-fir-fou-setting', '首页功能设置'],
  ['sleep-config', '睡眠配置'], ['sleep-status', '睡眠状态'], ['sleepmode', '睡眠模式'],
  ['sleepmodepara', '睡眠模式参数'], ['someone-appeared', '有人出现'], ['someone-at-the-door', '有人在门口'],
  ['sound-det-sens', '声音检测灵敏度'], ['sound-detection-switch', '声音检测开关'], ['split-room', '拆分房间'],
  ['src-level', '声源档位'], ['standby-effect', '待机效果'], ['standby-time', '待机时长'],
  ['start-build-map', '开始建图'], ['start-charge', '开始充电'], ['start-check', '开始检测'],
  ['start-custom-sweep', '开始自定义清扫'], ['start-dry', '开始烘干'], ['start-dust-arrest', '开始集尘'],
  ['start-eject', '开始弹卡'], ['start-hls-stream', '开始 HLS 拉流'], ['start-mop', '开始拖地'],
  ['start-mop-wash', '开始洗拖布'], ['start-only-sweep', '开始单扫'], ['start-p2p-stream', '开始 P2P 流'],
  ['start-rtsp-stream', '开始 RTSP 拉流'], ['start-sweep', '开始扫地'], ['start-sweep-mop', '开始扫拖'],
  ['start-user-define-sweep', '开始自定义清扫'], ['start-vacuum-room-sweep', '开始房间吸尘'],
  ['start-wash', '开始洗涤'], ['start-water-self-check', '开始水质自检'], ['start-zone-sweep', '开始区域清扫'],
  ['state', '状态'], ['stay-duration', '停留时长'], ['stop-alarm', '停止报警'],
  ['stop-and-gocharge', '停止并回充'], ['stop-build-map-and-gocharge', '停止建图并回充'],
  ['stop-check', '停止检测'], ['stop-dry', '停止烘干'], ['stop-intergration', '停止集成'],
  ['stop-mop-wash', '停止洗拖布'], ['stop-preservation', '停止保鲜'], ['stop-reserve', '取消预约'],
  ['stop-stream', '停止拉流'], ['stop-sweeping', '停止清扫'], ['stop-washing', '停止洗涤'],
  ['stop-working', '停止工作'], ['storage-free-space', '剩余空间'], ['storage-total-space', '总空间'],
  ['storage-used-space', '已用空间'], ['stream-address', '流地址'], ['stream-auth-token', '流鉴权令牌'],
  ['stream-receiver-id', '流接收端 ID'], ['stream-status', '流状态'], ['supportfunction', '支持的功能'],
  ['surge-power', '浪涌功率'], ['sw-flex-off-time', '智能关灯时间'], ['sw-timer-off', '定时关闭'],
  ['sw-timer-off-first', '定时关闭第 1 路'], ['sw-timer-off-second', '定时关闭第 2 路'],
  ['sw-timer-off-third', '定时关闭第 3 路'], ['sw-timer-off-fouth', '定时关闭第 4 路'],
  ['sweep-break-switch', '断点续扫开关'], ['sweep-complete', '清扫完成'], ['sweep-furniture', '家具清扫'],
  ['sweep-mop-type', '扫拖类型'], ['sweep-route', '清扫路线'], ['sweep-type', '清扫类型'],
  ['switch-dual-ctrl', '双路控制'], ['switch-event', '开关事件'], ['switch-mode-set', '开关模式设置'],
  ['switch-mutex', '开关互锁'], ['switch-one-fo-mode', '单火模式'], ['switch-sensor', '开关感应器'],
  ['switch-sensor-for-ble', '蓝牙开关感应器'], ['switch-toggle', '开关切换'], ['sync-manual-check', '同步人工检查'],
  ['talk-codec', '对讲编码'], ['talk-mode', '对讲模式'], ['target-voice', '目标音色'], ['task-switch', '任务开关'],
  ['temperature-alarm', '温度报警'], ['test', '测试'], ['text-content', '文本内容'], ['theme', '主题'],
  ['themesupport', '支持主题'], ['time-correct', '时间校准'], ['time-frame-screen', '定时熄屏'],
  ['time-watermark', '时间水印'], ['toggle-light-mode', '切换灯光模式'], ['top-resolution-type', '最高分辨率'],
  ['touch-sound', '触摸提示音'], ['touchuan', '透传'], ['trajectory-obj-name', '轨迹名称'],
  ['travel-point', '巡航点'], ['try-listen', '试听'], ['tv-switch', '电视开关'], ['tv-switchon', '电视开机'],
  ['tx-one', '发送一'], ['txone', '发送一'], ['tx-two', '发送二'], ['ui-support', '界面支持'],
  ['unix', 'Unix 时间'], ['unixtime', 'Unix 时间戳'], ['unlock-tone-volume', '开锁提示音量'],
  ['updata-difference', '升级差分包'], ['update-properties-data', '更新属性数据'], ['upload-video', '上传视频'],
  ['use-detergent', '使用洗涤剂'], ['user-define-sweep-cfg', '自定义清扫配置'], ['user-define-sweep-id', '自定义清扫 ID'],
  ['user-save', '用户保存'], ['vacuum', '吸尘'], ['vacuum-frameware-version', '扫地机固件版本'],
  ['vacuum-map', '清扫地图'], ['vacuum-position', '扫地机位置'], ['vacuum-room-ids', '清扫房间 ID'],
  ['vacuum-route', '清扫路径'], ['vendor', '厂商'], ['ventilation-high', '换气高档'],
  ['ventilation-keep', '换气保持'], ['ventilation-low', '换气低档'], ['venting-overtime', '换气超时'],
  ['very-dark-brightness', '极暗亮度'], ['video-attribute', '视频参数'], ['video-codec', '视频编码'],
  ['video-codec-type', '视频编码类型'], ['video-message', '视频消息'], ['vip-offset-num', '会员偏移量'],
  ['virtual-event', '虚拟事件'], ['virtual-fence', '虚拟围栏'], ['virtual-fence-area', '虚拟围栏区域'],
  ['virtual-fence-live', '虚拟围栏画面'], ['virtual-fence-switch', '虚拟围栏开关'], ['virtual-param', '虚拟参数'],
  ['virtual-service', '虚拟服务'], ['voice-management', '语音管理'], ['voice-url', '语音地址'],
  ['wachat-info', '微信信息'], ['wake-config', '唤醒配置'], ['wake-up', '唤醒'], ['wake-up-mode', '唤醒模式'],
  ['wakeupmodepara', '唤醒模式参数'], ['wallpaper', '壁纸'], ['wash-continue', '继续洗涤'],
  ['wash-end', '洗涤结束'], ['wash-end-reminder', '洗涤结束提醒'], ['wash-start', '洗涤开始'],
  ['water-check-list', '水质检测清单'], ['water-check-status', '水质检测状态'],
  ['water-output-for-washing-mop', '洗拖布出水量'], ['water-softener-left-level', '软水盐余量'],
  ['water-softener-management', '软水盐管理'], ['wdr-mode', '宽动态模式'], ['weather-refresh', '天气刷新'],
  ['wechat-unauthorized', '微信未授权'], ['wfxx', '天气信息'], ['whole-journey-time', '全程时长'],
  ['wifi-online', 'Wi-Fi 在线'], ['wifi-ssid', 'Wi-Fi 名称'], ['wiring-method', '接线方式'],
  ['word-type', '词类型'], ['working-time', '工作时长'], ['yl-bath', '浴霸'], ['zone-ids', '区域 ID'],
  ['zoom-close-up-function-switch', '变焦特写开关'], ['zoom-ratio', '变焦倍数'],
  // ---- 系列词条（厂商批量命名）----
  ...seq('生物节律相位', 'biorhythmphasetime', 'abcdefghi'),
  ...seq('生物节律状态', 'biorhythphasestate', 'abcdefghi'),
  ...seq('遥控数据', 'e-rmt', 'abcdefgh', ''),
  ...seq('遥控器', 'rmt', 'abcdefgh', ''),
  ...seq('遥控器', 'remote', 'abcdefgh'),
  ...seq('遥控器', 'remoter', 'abcdefgh'),
  ...seq('遥控地址', 'remoteadr', 'abcdef', ''),
  ...seq('数据', 'data', 'abcdefghij'),
  ...seq('灯光模式', 'light-mode', 'abcde'),
  ['light-mode-one', '灯光模式一'], ['light-mode-two', '灯光模式二'], ['light-mode-three', '灯光模式三'],
  ['light-mode-four', '灯光模式四'],
  ['my-scene-one', '我的场景一'], ['my-scene-two', '我的场景二'], ['my-scene-three', '我的场景三'],
  ['my-scene-four', '我的场景四'], ['my-scene-five', '我的场景五'], ['my-scene-six', '我的场景六'],
  ['my-scene-seven', '我的场景七'], ['my-scene-eight', '我的场景八'],
  ['message-one', '消息一'], ['message-two', '消息二'], ['message-three', '消息三'], ['message-four', '消息四'],
  ['key-name-one', '按键名称一'], ['key-name-two', '按键名称二'], ['key-name-three', '按键名称三'],
  ['key-name-four', '按键名称四'],
  ...seq('呼吸灯控制', 'breathinglumctl', 'ab'),
  ...seq('凹槽灯控制', 'groovelumctl', 'ab'),
];

const ENUM_PAIRS = [
  ['0 second', '0 秒'], ['1 minute', '1 分钟'], ['2 minute', '2 分钟'], ['2 minutes', '2 分钟'],
  ['3 minute', '3 分钟'], ['5 minute', '5 分钟'], ['5 minutes', '5 分钟'], ['10 minutes', '10 分钟'],
  ['20 minutes', '20 分钟'], ['30 minutes', '30 分钟'], ['2 hours', '2 小时'], ['3 hours', '3 小时'],
  ['4 hours', '4 小时'], ['7 sweeps', '7 次清扫'], ['5 second', '5 秒'], ['10 second', '10 秒'],
  ['15 second', '15 秒'], ['20 second', '20 秒'], ['30 second', '30 秒'], ['60 second', '60 秒'],
  ['120 second', '120 秒'], ['180 second', '180 秒'], ['second 10', '10 秒'], ['second 15', '15 秒'],
  ['second 20', '20 秒'], ['stay 0 second', '停留 0 秒'], ['stay 6 second', '停留 6 秒'],
  ['stay 10 second', '停留 10 秒'], ['stay 15 second', '停留 15 秒'], ['stay 20 second', '停留 20 秒'],
  ['stay 30 second', '停留 30 秒'], ['stay 60 second', '停留 60 秒'],
  ['aa  battery installed', 'AA 电池已装入'], ['aa battery remove', 'AA 电池已取出'],
  ['abnormal', '异常'], ['abnormal fingerprint sensor', '指纹传感器异常'], ['abnormal voltage', '电压异常'],
  ['aborting', '正在中止'], ['above the clouds', '云端之上（表盘）'], ['acc', 'ACC 供电'],
  ['add object', '添加对象'], ['album loop', '专辑循环'], ['album random play', '专辑随机播放'],
  ['all record', '全天录像'], ['anti-blue', '防蓝光'], ['apply fail', '应用失败'], ['apply success', '应用成功'],
  ['aquastopoccured', '水浸保护触发'], ['area', '区域'], ['area left', '左区'], ['area mid', '中区'],
  ['area right', '右区'], ['auto', '自动'], ['available', '可用'], ['avoid', '避让'], ['await show', '待展示'],
  ['basic', '基础'], ['battery high temperature alarm', '电池高温报警'], ['beat', '节拍'],
  ['beat of breath', '呼吸节拍'], ['ble outdoor', '蓝牙户外'], ['breakcharging', '充电中断'],
  ['breath', '呼吸'], ['breathing', '呼吸中'], ['brightness-switch', '亮度开关'], ['broken', '已损坏'],
  ['buildingmap', '建图中'], ['busy', '忙碌'], ['button unlock inside', '室内按键开锁'],
  ['by area', '按区域'], ['by room', '按房间'], ['calibration', '校准'], ['calling', '通话中'],
  ['cannel share', '取消共享'], ['card damage', '卡已损坏'], ['card is full', '卡已满'], ['careful', '精细'],
  ['cat', '猫'], ['charged', '已充电'], ['charged full', '已充满'], ['charging', '充电中'],
  ['check fail', '检测失败'], ['check success', '检测成功'], ['checking', '检测中'], ['chinese', '中文'],
  ['clear', '清除'], ['clearpoint', '清除点位'], ['close', '关'], ['close door', '关门'],
  ['close the door', '关门'], ['closed', '已关闭'], ['closing', '关闭中'], ['coerce', '强制'],
  ['colortemperatre-dec', '色温−'], ['colortemperature-add', '色温+'], ['colortemperature-sw', '色温开关'],
  ['completed', '已完成'], ['computer', '电脑'], ['continue record', '连续录像'], ['control', '控制'],
  ['cool', '制冷'], ['costum', '自定义'], ['custom area', '自定义区域'], ['daily', '每天'],
  ['daily wash', '日常洗'], ['day', '白天'], ['decontrol', '解除管控'], ['decrease', '减小'],
  ['deep', '深度'], ['default', '默认'], ['default-state', '默认状态'], ['defog', '除雾'], ['delay', '延时'],
  ['delete object', '删除对象'], ['digest', 'Digest 鉴权'], ['disable the away from home mode', '关闭离家模式'],
  ['disabled child lock', '童锁已关'], ['disabled child lock and from inside', '童锁与内锁已关'],
  ['disenable', '禁用'], ['display', '显示'], ['dog', '狗'], ['dog head', '狗头画面'], ['done', '完成'],
  ['door closed properly after left ajar', '门虚掩后已关好'], ['door lock batteries are low', '门锁电量低'],
  ['door lock batteries are nearly depleted', '门锁电量即将耗尽'],
  ['door lock camera batteries are low', '门锁摄像头电量低'],
  ['door lock camera batteries are nearly depleted', '门锁摄像头电量即将耗尽'],
  ['door lock was damaged', '门锁被破坏'], ['door lock was reset', '门锁被重置'],
  ['door not close', '门未关'], ['door stuck', '门卡住'], ['door was ajar', '门虚掩'],
  ['double verification', '双重验证'], ['download fail', '下载失败'], ['downloaded', '已下载'],
  ['downloading', '下载中'], ['dry', '干燥'], ['dual channel', '双声道'], ['dusk', '黄昏'],
  ['dynamic record', '移动侦测录像'], ['edge', '沿边'], ['effective work', '有效工作'],
  ['eight square  meters', '8 平方米以上'], ['eject', '弹出'], ['ejected', '已弹出'], ['ejecting', '弹出中'],
  ['enable', '启用'], ['enable the away from home mode', '开启离家模式'], ['enabled child lock', '童锁已开'],
  ['enabled child lock and from inside', '童锁与内锁已开'], ['energy saving', '节能'], ['english', '英文'],
  ['entertainment', '娱乐'], ['error', '错误'], ['every time', '每次'], ['eye protection', '护眼'],
  ['face', '人脸'], ['fan', '送风'], ['fan-error', '风扇故障'], ['fault', '故障'], ['faults', '故障'],
  ['favorite', '收藏'], ['few', '少量'], ['file err', '文件错误'], ['file error', '文件错误'],
  ['finger heart', '比心手势'], ['finger print', '指纹'], ['fingerprint', '指纹'], ['first button', '第 1 键'],
  ['five square  meters', '5 平方米'], ['fixed point cruise', '定点巡航'], ['fixing', '修复中'],
  ['formating', '格式化中'], ['formatting', '格式化中'], ['four-six square meters', '4-6 平方米'],
  ['fourth button', '第 4 键'], ['frequent unlocking failed by fingerprint', '指纹频繁开锁失败'],
  ['frequent unlocking failed by multiple methods', '多种方式频繁开锁失败'],
  ['frequent unlocking failed by nfc', 'NFC 频繁开锁失败'],
  ['frequent unlocking failed by password', '密码频繁开锁失败'],
  ['frequent wrong fingerprint', '指纹频繁错误'], ['frequent wrong key', '按键频繁错误'],
  ['frequent wrong password', '密码频繁错误'], ['frequent wrong unlock', '频繁开锁错误'],
  ['full', '满'], ['full speed', '全速'], ['get', '获取'], ['global', '全局'], ['go charging', '回充'],
  ['gochargebreak', '回充中断'], ['gochargebuildingmap', '回充建图中'],
  ['golden brilliance', '金色光辉（表盘）'], ['gowash', '回洗'], ['gradient', '渐变'], ['groove', '凹槽灯'],
  ['happy moment', '欢乐时刻（表盘）'], ['heat', '制热'], ['hexagon', '六边形'], ['high', '高'],
  ['high coverage', '高覆盖'], ['hight', '高'], ['hospitality', '迎宾'], ['idle', '空闲'],
  ['idle hang up', '空闲挂断'], ['ignore', '忽略'], ['immediately', '立即'], ['in use', '使用中'],
  ['incompatible', '不兼容'], ['increase', '增大'], ['indoor', '室内'], ['item1', '项 1'],
  ['item2', '项 2'], ['item3', '项 3'], ['item4', '项 4'], ['item5', '项 5'], ['item6', '项 6'],
  ['key', '钥匙'], ['key not pulled out', '钥匙未拔出'], ['keyhole foreign body', '锁孔异物'],
  ['lack', '不足'], ['lan', '局域网'], ['lay mtain rge', '维持运行'],
  ['leaving the door open timed out', '开门超时未关'], ['left and right button', '左右键'],
  ['left button', '左键'], ['less collisions', '少碰撞'], ['less than four square meters', '4 平方米以下'],
  ['level1', '1 档'], ['level2', '2 档'], ['level3', '3 档'], ['level4', '4 档'],
  ['lift left', '左抬（手势）'], ['lift right', '右抬（手势）'], ['lift up', '上抬（手势）'],
  ['lifted up the door handle from outside to lock', '从门外提起门把手上锁'], ['lighting', '照明'],
  ['limitthird', '第三路限位'], ['limitthirdclr', '第三路限位清除'], ['limitthirdrun', '第三路限位运行'],
  ['lithium battery installed', '锂电池已装入'], ['lithium battery remove', '锂电池已取出'],
  ['lock', '上锁'], ['lock key', '锁定键'], ['locked', '已上锁'], ['locked from inside', '室内反锁'],
  ['lockpicking', '撬锁'], ['lots of', '大量'], ['low', '低'], ['lower', '更低'], ['lowerposition', '下限位'],
  ['manual', '手动'], ['manual indoor', '手动室内'], ['many', '多'], ['mappingpause', '建图暂停'],
  ['medium', '中等'], ['member', '成员'], ['meow meow star', '喵星球（表盘）'], ['middle', '中'],
  ['mobile phone', '手机'], ['model-1', '模式 1'], ['model-2', '模式 2'], ['model-3', '模式 3'],
  ['model-4', '模式 4'], ['mop', '拖地'], ['mopping', '拖地中'], ['more settings 1', '更多设置 1'],
  ['more settings 2', '更多设置 2'], ['more than eight square meters', '8 平方米以上'],
  ['motion record', '移动侦测录像'], ['multitaskrecharge', '多任务回充'],
  ['multitaskstationworking', '多任务基站在工作'], ['mute', '静音'],
  ['my mode-scenario 1', '我的模式场景 1'], ['my mode-scenario 2', '我的模式场景 2'],
  ['my mode-scenario 3', '我的模式场景 3'], ['my mode-scenario 4', '我的模式场景 4'], ['my-mode', '我的模式'],
  ['natural wind', '自然风'], ['neutral wire', '有零线'], ['night', '夜晚'], ['night light', '夜灯'],
  ['night reading', '夜间阅读'], ['no fault', '无故障'], ['no faults', '无故障'], ['no faults ', '无故障'],
  ['no neutral', '无零线'], ['no prompt', '无提示'], ['no record', '不录像'], ['no sensing', '无感应'],
  ['non existent', '未插卡'], ['non rectangular quadrilateral', '非矩形四边形'], ['none', '无'],
  ['normal', '正常'], ['not chargeable', '不可充电'], ['not charging', '未充电'],
  ['not compatible', '不兼容'], ['not downloaded', '未下载'], ['not enough space', '空间不足'],
  ['not exist', '不存在'], ['not send', '不发送'],
  ['not tell the inside or outside of the door', '无法区分门内外'],
  ['off', '关闭'], ['ok', '好'], ['once', '单次'], ['one time', '一次'], ['one time password', '一次性密码'],
  ['one-time password', '一次性密码'], ['one-way', '单向'], ['online', '在线'], ['open', '开'],
  ['open door', '开门'], ['open over time', '开门超时'], ['opening', '开启中'], ['other', '其他'],
  ['others', '其他'], ['outdoor', '室外'], ['outdoor ', '室外'], ['over temperature', '过温'],
  ['over-temperature', '过温'], ['overheat and overload', '过热过载'], ['overload', '过载'],
  ['overload and overheat', '过载过热'], ['pair', '配对'], ['palm', '掌形'], ['palm print', '掌纹'],
  ['panoramic cruise', '全景巡航'], ['password', '密码'], ['pause', '暂停'], ['paused', '已暂停'],
  ['pentagon', '五边形'], ['periodic password', '周期密码'], ['playing', '播放中'], ['point', '点位'],
  ['preservation', '保鲜'], ['press left', '左按'], ['press right', '右按'], ['press up', '上按'],
  ['preview', '预览'], ['prewashing', '预洗'], ['professional-setting', '专业设置'], ['quick', '快速'],
  ['quick defog', '快速除雾'], ['quick single click', '快速单击'], ['quick wash', '快速洗'], ['quiet', '安静'],
  ['random play', '随机播放'], ['reading', '阅读'], ['rectangle', '矩形'], ['rejection', '拒接'],
  ['released lock from inside', '室内解除反锁'], ['remote', '遥控'], ['remote-add', '添加遥控'],
  ['repairing', '修复中'], ['reset all params', '重置全部参数'], ['reset button pressed', '重置键被按下'],
  ['rest', '休息'], ['reversal', '反转'], ['rhythm', '律动'], ['right button', '右键'],
  ['ring 1', '铃声 1'], ['ring 2', '铃声 2'], ['ring 3', '铃声 3'], ['rinsh', '漂洗'],
  ['rose sunset', '玫瑰日落（表盘）'], ['save water', '节水'], ['scene 1', '场景 1'], ['scene 2', '场景 2'],
  ['scene 3', '场景 3'], ['scene 4', '场景 4'], ['screen off', '熄屏'], ['sd-format', 'SD 卡格式化中'],
  ['sd-no-inset', '未插 SD 卡'], ['sd-no-space', 'SD 卡已满'], ['sd-no-work', 'SD 卡故障'],
  ['sd-nomal', 'SD 卡正常'], ['sd-out', 'SD 卡已弹出'], ['self adaption', '自适应'],
  ['sense someone', '感应到人'], ['sensing no one', '感应无人'], ['set sail wind', '启航之风（表盘）'],
  ['silent', '静音'], ['single channel', '单声道'], ['single cycle', '单曲循环'], ['single loop', '单曲循环'],
  ['six-eight square meters', '6-8 平方米'], ['sleep', '睡眠'], ['sleeping', '睡眠中'], ['smart', '智能'],
  ['spacewalk', '太空漫步（表盘）'], ['staging', '暂存中'], ['standard', '标准'],
  ['standby screen saver', '待机屏保'], ['standby theme', '待机主题'],
  ['standby with the screen off', '熄屏待机'], ['stationworking', '基站在工作'],
  ['stepping down', '降档'], ['stepping up', '升档'], ['sterilization', '杀菌'], ['stop', '停止'],
  ['stop record', '停止录像'], ['straight wind', '直吹风'], ['strong', '强力'], ['sweep', '扫地'],
  ['sweep before mopping', '先扫后拖'], ['sweep mop', '扫拖'], ['sweeping', '扫地中'],
  ['sweeping and mopping', '扫拖中'], ['ten square  meters', '10 平方米'], ['thank', '致谢（表盘）'],
  ['the door is not closed well', '门未关好'],
  ['the lithium battery temperature is normal', '锂电池温度正常'],
  ['the lithium battery temperature is too high', '锂电池温度过高'],
  ['the pump is short circuited or disconnected', '水泵短路或断开'], ['third button', '第 3 键'],
  ['three time', '三次'], ['toggle', '切换'], ['triangle', '三角形'], ['triple', '三击'],
  ['turntable', '转盘'], ['tv', '电视'], ['twice', '两次'], ['two time', '两次'], ['two-way', '双向'],
  ['ultra clean washing', '超净洗'], ['unavailable', '不可用'], ['uncheck', '未勾选'],
  ['uninitialized', '未初始化'], ['unlock', '开锁'], ['unlock exception', '开锁异常'],
  ['unlock from inside after leaving home', '离家后从室内开锁'], ['unlocked', '已开锁'],
  ['unpair', '取消配对'], ['unread', '未读'], ['updating', '更新中'], ['upperposition', '上限位'],
  ['vast planet', '浩瀚星球（表盘）'], ['wakeup', '唤醒'], ['warmth', '温暖（表盘）'],
  ['washbreak', '洗涤中断'], ['washing', '洗涤中'], ['water draining malfunction', '排水故障'],
  ['weak', '弱'], ['wired and wireless', '有线+无线'], ['wireless', '无线'], ['wireless 2 g', '无线 2.4G'],
  ['wireless 5 g', '无线 5G'], ['yeah', '是（表盘）'], ['zone', '区域'],
];

const ALL = [...NAME_PAIRS, ...ENUM_PAIRS];
// 去重（同键取先出现的）并统一小写键
const MAP = new Map();
for (const [en, z] of ALL) if (en && z && !MAP.has(en.toLowerCase())) MAP.set(en.toLowerCase(), z);

function getTerms() {
  return { count: MAP.size, pairs: [...MAP.entries()].map(([en, zh]) => [en, zh]).sort((a, b) => a[0].localeCompare(b[0])) };
}
module.exports = { getTerms, termZh: (k) => (k ? MAP.get(String(k).trim().toLowerCase()) || '' : '') };
